format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$character"""
add_newline = true
scan_timeout = 10

[container]
disabled = true

[aws]
disabled = true

[package]
disabled = true
