# #######################
# Dropping to the Shell
# ######################
[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

# If you also using Yazi on Windows:
[[mgr.prepend_keymap]]
on   = "!"
for  = "windows"
run  = 'shell "powershell.exe" --block'
desc = "Open PowerShell here"


# #######################
# Close input by ESC
# ######################
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

# #######################
# Smart Enter
# ######################
[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# #######################
# Paste into directory
# ######################
[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"
