#### Keybindings ####
#
# WARN: Do not use Alt(M-) here as it will cause key conflicts with yazi
#
# prefix
# C-Space (not suit for windows)
unbind C-b
set -g prefix C-a
bind C-Space send-prefix
# session management
bind S command-prompt "rename-session %%"
bind N command-prompt -p "New Session:" "new-session -s '%%'"
# window management
bind r command-prompt "rename-window %%"
bind X kill-pane
bind [ previous-window
bind ] next-window
bind '{' swap-window -t -1 \; select-window -t -1
bind '}' swap-window -t +1 \; select-window -t +1
# panel management
bind x kill-pane 
unbind %
bind '\' split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"
bind p run-shell ~/.config/tmux/scripts/swap-pane.sh
# bind f display-popup -E -w 80% -h 60% -x 10% -y 10% -T "Floating Shell" "$SHELL"
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# reload config
bind R source-file ~/.config/tmux/tmux.conf
# copy mode
bind ';' copy-mode
bind -T copy-mode-vi v send-key -X begin-selection
bind -T copy-mode-vi C-v send-key -X rectangle-toggle
bind -T copy-mode-vi y send-key -X copy-selection-and-cancel


#### Theme ####
source-file ~/.config/tmux/theme.conf

#### Plugins ####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

#### Settings ####
set -g mouse on
set -g history-limit 100000
set -g mode-keys vi
set -g base-index 1 # start index windwos at 1 not 0
set -g pane-base-index 1
set -sg escape-time 0
set -sa terminal-overrides ',xterm*:Tc'
# set -sa terminal-overrides ',xterm-256color:RGB'
set -g renumber-windows on
set -g status-position top
# yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
# restore
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# bootstrap tpm
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
